spring.config.import=optional:file:./env.properties

spring.application.name=CAF-FAPI-Backend


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.super-admin.nome=${SUPER_ADMIN_NOME}
app.super-admin.cognome=${SUPER_ADMIN_COGNOME}
app.super-admin.codice-fiscale=${SUPER_ADMIN_CODICE_FISCALE}
app.super-admin.email=${SUPER_ADMIN_EMAIL}
app.super-admin.password=${SUPER_ADMIN_PASSWORD}