-- =========================================================
-- CAF FAPI
-- V1 - Creazione schema iniziale
-- PostgreSQL / Flyway
-- =========================================================

CREATE TABLE utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    cognome VARCHAR(80) NOT NULL,
    codice_fiscale VARCHAR(16) NOT NULL,
    data_nascita DATE,
    luogo_nascita VARCHAR(100),
    email VARCHAR(150) NOT NULL,
    telefono VARCHAR(20),
    indirizzo VARCHAR(150),
    comune VARCHAR(100),
    provincia VARCHAR(2),
    cap VARCHAR(5),
    password VARCHAR(255) NOT NULL,
    ruolo VARCHAR(30) NOT NULL,
    attivo BOOLEAN NOT NULL DEFAULT TRUE,
    email_verificata BOOLEAN NOT NULL DEFAULT FALSE,
    account_bloccato BOOLEAN NOT NULL DEFAULT FALSE,
    tentativi_accesso_falliti INTEGER NOT NULL DEFAULT 0,
    mansione VARCHAR(100),
    numero_matricola VARCHAR(50),
    url_immagine_profilo VARCHAR(500),
    ultimo_accesso TIMESTAMP,
    password_modificata_il TIMESTAMP,
    creato_il TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aggiornato_il TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_utenti_codice_fiscale UNIQUE (codice_fiscale),
    CONSTRAINT uk_utenti_email UNIQUE (email),
    CONSTRAINT uk_utenti_numero_matricola UNIQUE (numero_matricola),
    CONSTRAINT chk_utenti_ruolo CHECK (ruolo IN ('SUPER_ADMIN', 'ADMIN', 'USER', 'CLIENTE'))
);

CREATE INDEX idx_utenti_ruolo ON utenti (ruolo);
CREATE INDEX idx_utenti_cognome_nome ON utenti (cognome, nome);

CREATE TABLE token_reset_password (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    utente_id BIGINT NOT NULL,
    scadenza TIMESTAMP NOT NULL,
    usato_il TIMESTAMP,
    creato_il TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_token_reset_password_hash UNIQUE (token_hash),
    CONSTRAINT fk_token_reset_password_utente
        FOREIGN KEY (utente_id) REFERENCES utenti (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_token_reset_password_hash ON token_reset_password (token_hash);
CREATE INDEX idx_token_reset_password_utente ON token_reset_password (utente_id);

CREATE TABLE "macro_aree"(
    "id" bigserial NOT NULL,
    "nome" VARCHAR(120) NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "descrizione_breve" VARCHAR(255) NULL,
    "descrizione" TEXT NULL,
    "chiave_icona" VARCHAR(60) NULL,
    "chiave_colore" VARCHAR(30) NULL,
    "ordine_visualizzazione" INTEGER NOT NULL,
    "attiva" BOOLEAN NOT NULL DEFAULT TRUE,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "aggiornato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE
    "macro_aree" ADD PRIMARY KEY("id");
ALTER TABLE
    "macro_aree" ADD CONSTRAINT "macro_aree_slug_unique" UNIQUE("slug");
CREATE TABLE "partner"(
    "id" bigserial NOT NULL,
    "nome" VARCHAR(120) NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "percorso_logo" VARCHAR(255) NULL,
    "sito_web" VARCHAR(255) NULL,
    "descrizione" TEXT NULL,
    "ordine_visualizzazione" INTEGER NOT NULL,
    "attivo" BOOLEAN NOT NULL DEFAULT TRUE,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "aggiornato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE
    "partner" ADD PRIMARY KEY("id");
ALTER TABLE
    "partner" ADD CONSTRAINT "partner_slug_unique" UNIQUE("slug");
CREATE TABLE "servizi"(
    "id" bigserial NOT NULL,
    "macro_area_id" BIGINT NOT NULL,
    "partner_id" BIGINT NULL,
    "nome" VARCHAR(150) NOT NULL,
    "slug" VARCHAR(150) NOT NULL,
    "descrizione_breve" VARCHAR(255) NULL,
    "descrizione" TEXT NULL,
    "destinatari" TEXT NULL,
    "requisiti" TEXT NULL,
    "come_funziona" TEXT NULL,
    "prezzo_testo" VARCHAR(255) NULL,
    "nota_prezzo" TEXT NULL,
    "durata_minuti" INTEGER NULL,
    "prenotabile" BOOLEAN NOT NULL DEFAULT FALSE,
    "richiedibile_online" BOOLEAN NOT NULL DEFAULT TRUE,
    "in_evidenza" BOOLEAN NOT NULL DEFAULT FALSE,
    "ordine_visualizzazione" INTEGER NOT NULL,
    "attivo" BOOLEAN NOT NULL DEFAULT TRUE,
    "valido_fino_al" DATE NULL,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "aggiornato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "servizi_macro_area_id_ordine_visualizzazione_index" ON
    "servizi"(
        "macro_area_id",
        "ordine_visualizzazione"
    );
ALTER TABLE
    "servizi" ADD PRIMARY KEY("id");
ALTER TABLE
    "servizi" ADD CONSTRAINT "servizi_slug_unique" UNIQUE("slug");
CREATE TABLE "pratiche"(
    "id" bigserial NOT NULL,
    "numero_pratica" VARCHAR(30) NOT NULL,
    "utente_id" BIGINT NOT NULL,
    "servizio_id" BIGINT NOT NULL,
    "assegnata_a_id" BIGINT NULL,
    "oggetto" VARCHAR(200) NOT NULL,
    "descrizione" TEXT NULL,
    "stato" VARCHAR(40) NOT NULL DEFAULT 'nuova',
    "priorita" SMALLINT NOT NULL,
    "data_scadenza" DATE NULL,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "aggiornato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "chiuso_il" TIMESTAMP NULL
);
CREATE INDEX "pratiche_stato_aggiornato_il_index" ON
    "pratiche"("stato", "aggiornato_il");
CREATE INDEX "pratiche_assegnata_a_id_stato_index" ON
    "pratiche"("assegnata_a_id", "stato");
CREATE INDEX "pratiche_utente_id_creato_il_index" ON
    "pratiche"("utente_id", "creato_il");
ALTER TABLE
    "pratiche" ADD PRIMARY KEY("id");
ALTER TABLE
    "pratiche" ADD CONSTRAINT "pratiche_numero_pratica_unique" UNIQUE("numero_pratica");
CREATE TABLE "storico_stati_pratica"(
    "id" bigserial NOT NULL,
    "pratica_id" BIGINT NOT NULL,
    "stato_precedente" VARCHAR(40) NULL,
    "nuovo_stato" VARCHAR(40) NOT NULL,
    "modificato_da_id" BIGINT NULL,
    "nota" TEXT NULL,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "storico_stati_pratica_pratica_id_creato_il_index" ON
    "storico_stati_pratica"("pratica_id", "creato_il");
ALTER TABLE
    "storico_stati_pratica" ADD PRIMARY KEY("id");
CREATE TABLE "messaggi_pratica"(
    "id" bigserial NOT NULL,
    "pratica_id" BIGINT NOT NULL,
    "autore_id" BIGINT NULL,
    "tipo" VARCHAR(30) NOT NULL DEFAULT 'cittadino',
    "contenuto" TEXT NOT NULL,
    "letto_il" TIMESTAMP NULL,
        "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "messaggi_pratica_pratica_id_creato_il_index" ON
    "messaggi_pratica"("pratica_id", "creato_il");
ALTER TABLE
    "messaggi_pratica" ADD PRIMARY KEY("id");
CREATE TABLE "documenti_richiesti_servizio"(
    "id" bigserial NOT NULL,
    "servizio_id" BIGINT NOT NULL,
    "etichetta" VARCHAR(150) NOT NULL,
    "suggerimento" TEXT NULL,
    "obbligatorio" BOOLEAN NOT NULL DEFAULT TRUE,
    "ordine_visualizzazione" INTEGER NOT NULL
);
ALTER TABLE
    "documenti_richiesti_servizio" ADD PRIMARY KEY("id");
CREATE TABLE "documenti_richiesti_pratica"(
    "id" bigserial NOT NULL,
    "pratica_id" BIGINT NOT NULL,
    "etichetta" VARCHAR(150) NOT NULL,
    "suggerimento" TEXT NULL,
    "obbligatorio" BOOLEAN NOT NULL DEFAULT TRUE,
    "stato" VARCHAR(30) NOT NULL DEFAULT 'mancante',
    "richiesto_da_id" BIGINT NULL,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "aggiornato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "documenti_richiesti_pratica_pratica_id_stato_index" ON
    "documenti_richiesti_pratica"("pratica_id", "stato");
ALTER TABLE
    "documenti_richiesti_pratica" ADD PRIMARY KEY("id");
CREATE TABLE "allegati"(
    "id" bigserial NOT NULL,
    "proprietario_id" BIGINT NOT NULL,
    "pratica_id" BIGINT NULL,
    "messaggio_id" BIGINT NULL,
    "documento_richiesto_id" BIGINT NULL,
    "nome_originale" VARCHAR(255) NOT NULL,
    "percorso_archiviazione" VARCHAR(500) NOT NULL,
    "tipo_mime" VARCHAR(120) NOT NULL,
    "dimensione_byte" BIGINT NOT NULL,
    "checksum_sha256" VARCHAR(64) NULL,
    "categoria" VARCHAR(60) NULL,
    "stato" VARCHAR(30) NOT NULL DEFAULT 'caricato',
    "caricato_da_id" BIGINT NULL,
    "verificato_da_id" BIGINT NULL,
    "verificato_il" TIMESTAMP NULL,
        "motivo_rifiuto" TEXT NULL,
        "firma_richiesta" BOOLEAN NOT NULL DEFAULT FALSE,
        "firmato_il" TIMESTAMP NULL,
        "conserva_fino_al" DATE NULL,
        "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "eliminato_il" TIMESTAMP NULL
);
ALTER TABLE
    "allegati" ADD PRIMARY KEY("id");
CREATE INDEX "allegati_pratica_id_index" ON
    "allegati"("pratica_id");
CREATE TABLE "scadenze"(
    "id" bigserial NOT NULL,
    "utente_id" BIGINT NOT NULL,
    "pratica_id" BIGINT NULL,
    "titolo" VARCHAR(150) NOT NULL,
    "data_scadenza" DATE NOT NULL,
    "completata" BOOLEAN NOT NULL DEFAULT FALSE,
    "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "scadenze_utente_id_data_scadenza_index" ON
    "scadenze"("utente_id", "data_scadenza");
ALTER TABLE
    "scadenze" ADD PRIMARY KEY("id");
CREATE TABLE "appuntamenti"(
    "id" bigserial NOT NULL,
    "utente_id" BIGINT NOT NULL,
    "servizio_id" BIGINT NULL,
    "pratica_id" BIGINT NULL,
    "operatore_id" BIGINT NULL,
    "inizio_il" TIMESTAMP NOT NULL,
        "fine_il" TIMESTAMP NOT NULL,
        "stato" VARCHAR(30) NOT NULL DEFAULT 'richiesto',
        "sede" VARCHAR(150) NOT NULL DEFAULT 'CAF FAPI Pianopoli',
        "nota" TEXT NULL,
        "annullato_da_id" BIGINT NULL,
        "motivo_annullamento" TEXT NULL,
        "promemoria_inviato_il" TIMESTAMP NULL,
        "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "aggiornato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "appuntamenti_operatore_id_inizio_il_index" ON
    "appuntamenti"("operatore_id", "inizio_il");
CREATE INDEX "appuntamenti_utente_id_inizio_il_index" ON
    "appuntamenti"("utente_id", "inizio_il");
ALTER TABLE
    "appuntamenti" ADD PRIMARY KEY("id");
CREATE TABLE "messaggi_contatto"(
    "id" bigserial NOT NULL,
    "utente_id" BIGINT NULL,
    "nome" VARCHAR(150) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "telefono" VARCHAR(30) NULL,
    "oggetto" VARCHAR(200) NOT NULL,
    "messaggio" TEXT NOT NULL,
    "stato" VARCHAR(30) NOT NULL DEFAULT 'nuovo',
    "gestito_da_id" BIGINT NULL,
    "letto_il" TIMESTAMP NULL,
        "creato_il" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "messaggi_contatto_stato_creato_il_index" ON
    "messaggi_contatto"("stato", "creato_il");
ALTER TABLE
    "messaggi_contatto" ADD PRIMARY KEY("id");
ALTER TABLE
    "servizi" ADD CONSTRAINT "servizi_partner_id_foreign" FOREIGN KEY("partner_id") REFERENCES "partner"("id");
ALTER TABLE
    "storico_stati_pratica" ADD CONSTRAINT "storico_stati_pratica_pratica_id_foreign" FOREIGN KEY("pratica_id") REFERENCES "pratiche"("id");
ALTER TABLE
    "scadenze" ADD CONSTRAINT "scadenze_utente_id_foreign" FOREIGN KEY("utente_id") REFERENCES "utenti"("id");
ALTER TABLE
    "allegati" ADD CONSTRAINT "allegati_caricato_da_id_foreign" FOREIGN KEY("caricato_da_id") REFERENCES "utenti"("id");
ALTER TABLE
    "messaggi_pratica" ADD CONSTRAINT "messaggi_pratica_pratica_id_foreign" FOREIGN KEY("pratica_id") REFERENCES "pratiche"("id");
ALTER TABLE
    "appuntamenti" ADD CONSTRAINT "appuntamenti_servizio_id_foreign" FOREIGN KEY("servizio_id") REFERENCES "servizi"("id");
ALTER TABLE
    "allegati" ADD CONSTRAINT "allegati_messaggio_id_foreign" FOREIGN KEY("messaggio_id") REFERENCES "messaggi_pratica"("id");
ALTER TABLE
    "documenti_richiesti_servizio" ADD CONSTRAINT "documenti_richiesti_servizio_servizio_id_foreign" FOREIGN KEY("servizio_id") REFERENCES "servizi"("id");
ALTER TABLE
    "servizi" ADD CONSTRAINT "servizi_macro_area_id_foreign" FOREIGN KEY("macro_area_id") REFERENCES "macro_aree"("id");
ALTER TABLE
    "pratiche" ADD CONSTRAINT "pratiche_servizio_id_foreign" FOREIGN KEY("servizio_id") REFERENCES "servizi"("id");
ALTER TABLE
    "scadenze" ADD CONSTRAINT "scadenze_pratica_id_foreign" FOREIGN KEY("pratica_id") REFERENCES "pratiche"("id");
ALTER TABLE
    "messaggi_pratica" ADD CONSTRAINT "messaggi_pratica_autore_id_foreign" FOREIGN KEY("autore_id") REFERENCES "utenti"("id");
ALTER TABLE
    "allegati" ADD CONSTRAINT "allegati_documento_richiesto_id_foreign" FOREIGN KEY("documento_richiesto_id") REFERENCES "documenti_richiesti_pratica"("id");
ALTER TABLE
    "storico_stati_pratica" ADD CONSTRAINT "storico_stati_pratica_modificato_da_id_foreign" FOREIGN KEY("modificato_da_id") REFERENCES "utenti"("id");
ALTER TABLE
    "allegati" ADD CONSTRAINT "allegati_pratica_id_foreign" FOREIGN KEY("pratica_id") REFERENCES "pratiche"("id");
ALTER TABLE
    "allegati" ADD CONSTRAINT "allegati_verificato_da_id_foreign" FOREIGN KEY("verificato_da_id") REFERENCES "utenti"("id");
ALTER TABLE
    "appuntamenti" ADD CONSTRAINT "appuntamenti_utente_id_foreign" FOREIGN KEY("utente_id") REFERENCES "utenti"("id");
ALTER TABLE
    "appuntamenti" ADD CONSTRAINT "appuntamenti_operatore_id_foreign" FOREIGN KEY("operatore_id") REFERENCES "utenti"("id");
ALTER TABLE
    "appuntamenti" ADD CONSTRAINT "appuntamenti_pratica_id_foreign" FOREIGN KEY("pratica_id") REFERENCES "pratiche"("id");
ALTER TABLE
    "messaggi_contatto" ADD CONSTRAINT "messaggi_contatto_gestito_da_id_foreign" FOREIGN KEY("gestito_da_id") REFERENCES "utenti"("id");
ALTER TABLE
    "allegati" ADD CONSTRAINT "allegati_proprietario_id_foreign" FOREIGN KEY("proprietario_id") REFERENCES "utenti"("id");
ALTER TABLE
    "pratiche" ADD CONSTRAINT "pratiche_utente_id_foreign" FOREIGN KEY("utente_id") REFERENCES "utenti"("id");
ALTER TABLE
    "appuntamenti" ADD CONSTRAINT "appuntamenti_annullato_da_id_foreign" FOREIGN KEY("annullato_da_id") REFERENCES "utenti"("id");
ALTER TABLE
    "documenti_richiesti_pratica" ADD CONSTRAINT "documenti_richiesti_pratica_pratica_id_foreign" FOREIGN KEY("pratica_id") REFERENCES "pratiche"("id");
ALTER TABLE
    "pratiche" ADD CONSTRAINT "pratiche_assegnata_a_id_foreign" FOREIGN KEY("assegnata_a_id") REFERENCES "utenti"("id");
ALTER TABLE
    "documenti_richiesti_pratica" ADD CONSTRAINT "documenti_richiesti_pratica_richiesto_da_id_foreign" FOREIGN KEY("richiesto_da_id") REFERENCES "utenti"("id");
ALTER TABLE
    "messaggi_contatto" ADD CONSTRAINT "messaggi_contatto_utente_id_foreign" FOREIGN KEY("utente_id") REFERENCES "utenti"("id");